/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Account
 */
public class AccountTest {
    private final Account model = new Account();

    /**
     * Model tests for Account
     */
    @Test
    public void testAccount() {
        // TODO: test Account
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'domainName'
     */
    @Test
    public void domainNameTest() {
        // TODO: test domainName
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'billingEmail'
     */
    @Test
    public void billingEmailTest() {
        // TODO: test billingEmail
    }

    /**
     * Test the property 'planName'
     */
    @Test
    public void planNameTest() {
        // TODO: test planName
    }

    /**
     * Test the property 'planExpires'
     */
    @Test
    public void planExpiresTest() {
        // TODO: test planExpires
    }

    /**
     * Test the property 'applicationLimit'
     */
    @Test
    public void applicationLimitTest() {
        // TODO: test applicationLimit
    }

    /**
     * Test the property 'userLimit'
     */
    @Test
    public void userLimitTest() {
        // TODO: test userLimit
    }

    /**
     * Test the property 'campaignLimit'
     */
    @Test
    public void campaignLimitTest() {
        // TODO: test campaignLimit
    }

    /**
     * Test the property 'apiLimit'
     */
    @Test
    public void apiLimitTest() {
        // TODO: test apiLimit
    }

    /**
     * Test the property 'applicationCount'
     */
    @Test
    public void applicationCountTest() {
        // TODO: test applicationCount
    }

    /**
     * Test the property 'userCount'
     */
    @Test
    public void userCountTest() {
        // TODO: test userCount
    }

    /**
     * Test the property 'campaignsActiveCount'
     */
    @Test
    public void campaignsActiveCountTest() {
        // TODO: test campaignsActiveCount
    }

    /**
     * Test the property 'campaignsInactiveCount'
     */
    @Test
    public void campaignsInactiveCountTest() {
        // TODO: test campaignsInactiveCount
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

}
