/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import one.talon.model.PrismaticEventPayloadLoyaltyProfileBasedPointsChangedNotificationAction;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PrismaticEventPayloadLoyaltyProfileBasedPointsChangedNotification
 */
public class PrismaticEventPayloadLoyaltyProfileBasedPointsChangedNotificationTest {
    private final PrismaticEventPayloadLoyaltyProfileBasedPointsChangedNotification model = new PrismaticEventPayloadLoyaltyProfileBasedPointsChangedNotification();

    /**
     * Model tests for PrismaticEventPayloadLoyaltyProfileBasedPointsChangedNotification
     */
    @Test
    public void testPrismaticEventPayloadLoyaltyProfileBasedPointsChangedNotification() {
        // TODO: test PrismaticEventPayloadLoyaltyProfileBasedPointsChangedNotification
    }

    /**
     * Test the property 'profileIntegrationID'
     */
    @Test
    public void profileIntegrationIDTest() {
        // TODO: test profileIntegrationID
    }

    /**
     * Test the property 'loyaltyProgramID'
     */
    @Test
    public void loyaltyProgramIDTest() {
        // TODO: test loyaltyProgramID
    }

    /**
     * Test the property 'subledgerID'
     */
    @Test
    public void subledgerIDTest() {
        // TODO: test subledgerID
    }

    /**
     * Test the property 'sourceOfEvent'
     */
    @Test
    public void sourceOfEventTest() {
        // TODO: test sourceOfEvent
    }

    /**
     * Test the property 'employeeName'
     */
    @Test
    public void employeeNameTest() {
        // TODO: test employeeName
    }

    /**
     * Test the property 'userID'
     */
    @Test
    public void userIDTest() {
        // TODO: test userID
    }

    /**
     * Test the property 'currentPoints'
     */
    @Test
    public void currentPointsTest() {
        // TODO: test currentPoints
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

    /**
     * Test the property 'publishedAt'
     */
    @Test
    public void publishedAtTest() {
        // TODO: test publishedAt
    }

}
