/*
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CustomerProfile;
import io.swagger.client.model.Entity;
import io.swagger.client.model.IntegrationEntity;
import io.swagger.client.model.LoyaltyMembership;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * ApplicationProfile
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-06T13:17:26.027+01:00")
public class ApplicationProfile {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("integrationId")
  private String integrationId = null;

  @SerializedName("attributes")
  private Object attributes = null;

  @SerializedName("accountId")
  private Integer accountId = null;

  @SerializedName("closedSessions")
  private Integer closedSessions = null;

  @SerializedName("totalSales")
  private BigDecimal totalSales = null;

  @SerializedName("loyaltyMemberships")
  private List<LoyaltyMembership> loyaltyMemberships = new ArrayList<LoyaltyMembership>();

  @SerializedName("lastActivity")
  private OffsetDateTime lastActivity = null;

  public ApplicationProfile id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID for this entity.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Unique ID for this entity.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ApplicationProfile created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * The exact moment this entity was created.
   * @return created
  **/
  @ApiModelProperty(required = true, value = "The exact moment this entity was created.")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public ApplicationProfile integrationId(String integrationId) {
    this.integrationId = integrationId;
    return this;
  }

   /**
   * The ID used for this entity in the application system.
   * @return integrationId
  **/
  @ApiModelProperty(required = true, value = "The ID used for this entity in the application system.")
  public String getIntegrationId() {
    return integrationId;
  }

  public void setIntegrationId(String integrationId) {
    this.integrationId = integrationId;
  }

  public ApplicationProfile attributes(Object attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Arbitrary properties associated with this item
   * @return attributes
  **/
  @ApiModelProperty(value = "Arbitrary properties associated with this item")
  public Object getAttributes() {
    return attributes;
  }

  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }

  public ApplicationProfile accountId(Integer accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * The ID of the Talon.One account that owns this profile.
   * @return accountId
  **/
  @ApiModelProperty(required = true, value = "The ID of the Talon.One account that owns this profile.")
  public Integer getAccountId() {
    return accountId;
  }

  public void setAccountId(Integer accountId) {
    this.accountId = accountId;
  }

  public ApplicationProfile closedSessions(Integer closedSessions) {
    this.closedSessions = closedSessions;
    return this;
  }

   /**
   * The total amount of closed sessions by a customer. A closed session is a successful purchase.
   * @return closedSessions
  **/
  @ApiModelProperty(required = true, value = "The total amount of closed sessions by a customer. A closed session is a successful purchase.")
  public Integer getClosedSessions() {
    return closedSessions;
  }

  public void setClosedSessions(Integer closedSessions) {
    this.closedSessions = closedSessions;
  }

  public ApplicationProfile totalSales(BigDecimal totalSales) {
    this.totalSales = totalSales;
    return this;
  }

   /**
   * Sum of all purchases made by this customer
   * @return totalSales
  **/
  @ApiModelProperty(required = true, value = "Sum of all purchases made by this customer")
  public BigDecimal getTotalSales() {
    return totalSales;
  }

  public void setTotalSales(BigDecimal totalSales) {
    this.totalSales = totalSales;
  }

  public ApplicationProfile loyaltyMemberships(List<LoyaltyMembership> loyaltyMemberships) {
    this.loyaltyMemberships = loyaltyMemberships;
    return this;
  }

  public ApplicationProfile addLoyaltyMembershipsItem(LoyaltyMembership loyaltyMembershipsItem) {
    this.loyaltyMemberships.add(loyaltyMembershipsItem);
    return this;
  }

   /**
   * A list of loyalty programs joined by the customer
   * @return loyaltyMemberships
  **/
  @ApiModelProperty(required = true, value = "A list of loyalty programs joined by the customer")
  public List<LoyaltyMembership> getLoyaltyMemberships() {
    return loyaltyMemberships;
  }

  public void setLoyaltyMemberships(List<LoyaltyMembership> loyaltyMemberships) {
    this.loyaltyMemberships = loyaltyMemberships;
  }

  public ApplicationProfile lastActivity(OffsetDateTime lastActivity) {
    this.lastActivity = lastActivity;
    return this;
  }

   /**
   * Timestamp of the most recent event received from this customer
   * @return lastActivity
  **/
  @ApiModelProperty(required = true, value = "Timestamp of the most recent event received from this customer")
  public OffsetDateTime getLastActivity() {
    return lastActivity;
  }

  public void setLastActivity(OffsetDateTime lastActivity) {
    this.lastActivity = lastActivity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationProfile applicationProfile = (ApplicationProfile) o;
    return Objects.equals(this.id, applicationProfile.id) &&
        Objects.equals(this.created, applicationProfile.created) &&
        Objects.equals(this.integrationId, applicationProfile.integrationId) &&
        Objects.equals(this.attributes, applicationProfile.attributes) &&
        Objects.equals(this.accountId, applicationProfile.accountId) &&
        Objects.equals(this.closedSessions, applicationProfile.closedSessions) &&
        Objects.equals(this.totalSales, applicationProfile.totalSales) &&
        Objects.equals(this.loyaltyMemberships, applicationProfile.loyaltyMemberships) &&
        Objects.equals(this.lastActivity, applicationProfile.lastActivity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, created, integrationId, attributes, accountId, closedSessions, totalSales, loyaltyMemberships, lastActivity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationProfile {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    integrationId: ").append(toIndentedString(integrationId)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    closedSessions: ").append(toIndentedString(closedSessions)).append("\n");
    sb.append("    totalSales: ").append(toIndentedString(totalSales)).append("\n");
    sb.append("    loyaltyMemberships: ").append(toIndentedString(loyaltyMemberships)).append("\n");
    sb.append("    lastActivity: ").append(toIndentedString(lastActivity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

