/*
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CampaignSetNode;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CampaignSetBranchNode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-06T13:17:26.027+01:00")
public class CampaignSetBranchNode {
  /**
   * Indicates the node type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    SET("SET");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("name")
  private String name = null;

  /**
   * How does the set operates on its elements
   */
  @JsonAdapter(OperatorEnum.Adapter.class)
  public enum OperatorEnum {
    ALL("ALL"),
    
    FIRST("FIRST");

    private String value;

    OperatorEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OperatorEnum fromValue(String text) {
      for (OperatorEnum b : OperatorEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<OperatorEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OperatorEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OperatorEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return OperatorEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("operator")
  private OperatorEnum operator = null;

  @SerializedName("elements")
  private List<CampaignSetNode> elements = new ArrayList<CampaignSetNode>();

  public CampaignSetBranchNode type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Indicates the node type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Indicates the node type")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public CampaignSetBranchNode name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the set
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the set")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CampaignSetBranchNode operator(OperatorEnum operator) {
    this.operator = operator;
    return this;
  }

   /**
   * How does the set operates on its elements
   * @return operator
  **/
  @ApiModelProperty(required = true, value = "How does the set operates on its elements")
  public OperatorEnum getOperator() {
    return operator;
  }

  public void setOperator(OperatorEnum operator) {
    this.operator = operator;
  }

  public CampaignSetBranchNode elements(List<CampaignSetNode> elements) {
    this.elements = elements;
    return this;
  }

  public CampaignSetBranchNode addElementsItem(CampaignSetNode elementsItem) {
    this.elements.add(elementsItem);
    return this;
  }

   /**
   * Child elements of this set
   * @return elements
  **/
  @ApiModelProperty(required = true, value = "Child elements of this set")
  public List<CampaignSetNode> getElements() {
    return elements;
  }

  public void setElements(List<CampaignSetNode> elements) {
    this.elements = elements;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignSetBranchNode campaignSetBranchNode = (CampaignSetBranchNode) o;
    return Objects.equals(this.type, campaignSetBranchNode.type) &&
        Objects.equals(this.name, campaignSetBranchNode.name) &&
        Objects.equals(this.operator, campaignSetBranchNode.operator) &&
        Objects.equals(this.elements, campaignSetBranchNode.elements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, name, operator, elements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignSetBranchNode {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    elements: ").append(toIndentedString(elements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

