/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Provides statistics regarding an application&#39;s campaigns.
 */
@ApiModel(description = "Provides statistics regarding an application's campaigns.")

public class ApplicationCampaignStats {
  public static final String SERIALIZED_NAME_DISABLED = "disabled";
  @SerializedName(SERIALIZED_NAME_DISABLED)
  private Long disabled;

  public static final String SERIALIZED_NAME_STAGED = "staged";
  @SerializedName(SERIALIZED_NAME_STAGED)
  private Long staged;

  public static final String SERIALIZED_NAME_SCHEDULED = "scheduled";
  @SerializedName(SERIALIZED_NAME_SCHEDULED)
  private Long scheduled;

  public static final String SERIALIZED_NAME_RUNNING = "running";
  @SerializedName(SERIALIZED_NAME_RUNNING)
  private Long running;

  public static final String SERIALIZED_NAME_EXPIRED = "expired";
  @SerializedName(SERIALIZED_NAME_EXPIRED)
  private Long expired;

  public static final String SERIALIZED_NAME_ARCHIVED = "archived";
  @SerializedName(SERIALIZED_NAME_ARCHIVED)
  private Long archived;


  public ApplicationCampaignStats disabled(Long disabled) {
    
    this.disabled = disabled;
    return this;
  }

   /**
   * Number of disabled campaigns.
   * @return disabled
  **/
  @ApiModelProperty(required = true, value = "Number of disabled campaigns.")

  public Long getDisabled() {
    return disabled;
  }


  public void setDisabled(Long disabled) {
    this.disabled = disabled;
  }


  public ApplicationCampaignStats staged(Long staged) {
    
    this.staged = staged;
    return this;
  }

   /**
   * Number of staged campaigns.
   * @return staged
  **/
  @ApiModelProperty(required = true, value = "Number of staged campaigns.")

  public Long getStaged() {
    return staged;
  }


  public void setStaged(Long staged) {
    this.staged = staged;
  }


  public ApplicationCampaignStats scheduled(Long scheduled) {
    
    this.scheduled = scheduled;
    return this;
  }

   /**
   * Number of scheduled campaigns.
   * @return scheduled
  **/
  @ApiModelProperty(required = true, value = "Number of scheduled campaigns.")

  public Long getScheduled() {
    return scheduled;
  }


  public void setScheduled(Long scheduled) {
    this.scheduled = scheduled;
  }


  public ApplicationCampaignStats running(Long running) {
    
    this.running = running;
    return this;
  }

   /**
   * Number of running campaigns.
   * @return running
  **/
  @ApiModelProperty(required = true, value = "Number of running campaigns.")

  public Long getRunning() {
    return running;
  }


  public void setRunning(Long running) {
    this.running = running;
  }


  public ApplicationCampaignStats expired(Long expired) {
    
    this.expired = expired;
    return this;
  }

   /**
   * Number of expired campaigns.
   * @return expired
  **/
  @ApiModelProperty(required = true, value = "Number of expired campaigns.")

  public Long getExpired() {
    return expired;
  }


  public void setExpired(Long expired) {
    this.expired = expired;
  }


  public ApplicationCampaignStats archived(Long archived) {
    
    this.archived = archived;
    return this;
  }

   /**
   * Number of archived campaigns.
   * @return archived
  **/
  @ApiModelProperty(required = true, value = "Number of archived campaigns.")

  public Long getArchived() {
    return archived;
  }


  public void setArchived(Long archived) {
    this.archived = archived;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationCampaignStats applicationCampaignStats = (ApplicationCampaignStats) o;
    return Objects.equals(this.disabled, applicationCampaignStats.disabled) &&
        Objects.equals(this.staged, applicationCampaignStats.staged) &&
        Objects.equals(this.scheduled, applicationCampaignStats.scheduled) &&
        Objects.equals(this.running, applicationCampaignStats.running) &&
        Objects.equals(this.expired, applicationCampaignStats.expired) &&
        Objects.equals(this.archived, applicationCampaignStats.archived);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disabled, staged, scheduled, running, expired, archived);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationCampaignStats {\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    staged: ").append(toIndentedString(staged)).append("\n");
    sb.append("    scheduled: ").append(toIndentedString(scheduled)).append("\n");
    sb.append("    running: ").append(toIndentedString(running)).append("\n");
    sb.append("    expired: ").append(toIndentedString(expired)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

