/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import one.talon.model.AdjustmentDetails;
import one.talon.model.InfluencingCampaignDetails;

/**
 * Auxiliary data for found price observation.
 */
@ApiModel(description = "Auxiliary data for found price observation.")

public class BestPriorPriceMetadata {
  public static final String SERIALIZED_NAME_INFLUENCING_CAMPAIGN_DETAILS = "influencingCampaignDetails";
  @SerializedName(SERIALIZED_NAME_INFLUENCING_CAMPAIGN_DETAILS)
  private List<InfluencingCampaignDetails> influencingCampaignDetails = new ArrayList<InfluencingCampaignDetails>();

  public static final String SERIALIZED_NAME_ADJUSTMENT_DETAILS = "adjustmentDetails";
  @SerializedName(SERIALIZED_NAME_ADJUSTMENT_DETAILS)
  private AdjustmentDetails adjustmentDetails;


  public BestPriorPriceMetadata influencingCampaignDetails(List<InfluencingCampaignDetails> influencingCampaignDetails) {
    
    this.influencingCampaignDetails = influencingCampaignDetails;
    return this;
  }

  public BestPriorPriceMetadata addInfluencingCampaignDetailsItem(InfluencingCampaignDetails influencingCampaignDetailsItem) {
    this.influencingCampaignDetails.add(influencingCampaignDetailsItem);
    return this;
  }

   /**
   * Details about campaigns that influenced the final price.
   * @return influencingCampaignDetails
  **/
  @ApiModelProperty(required = true, value = "Details about campaigns that influenced the final price.")

  public List<InfluencingCampaignDetails> getInfluencingCampaignDetails() {
    return influencingCampaignDetails;
  }


  public void setInfluencingCampaignDetails(List<InfluencingCampaignDetails> influencingCampaignDetails) {
    this.influencingCampaignDetails = influencingCampaignDetails;
  }


  public BestPriorPriceMetadata adjustmentDetails(AdjustmentDetails adjustmentDetails) {
    
    this.adjustmentDetails = adjustmentDetails;
    return this;
  }

   /**
   * Get adjustmentDetails
   * @return adjustmentDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AdjustmentDetails getAdjustmentDetails() {
    return adjustmentDetails;
  }


  public void setAdjustmentDetails(AdjustmentDetails adjustmentDetails) {
    this.adjustmentDetails = adjustmentDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BestPriorPriceMetadata bestPriorPriceMetadata = (BestPriorPriceMetadata) o;
    return Objects.equals(this.influencingCampaignDetails, bestPriorPriceMetadata.influencingCampaignDetails) &&
        Objects.equals(this.adjustmentDetails, bestPriorPriceMetadata.adjustmentDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(influencingCampaignDetails, adjustmentDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BestPriorPriceMetadata {\n");
    sb.append("    influencingCampaignDetails: ").append(toIndentedString(influencingCampaignDetails)).append("\n");
    sb.append("    adjustmentDetails: ").append(toIndentedString(adjustmentDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

