/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The campaign position within the evaluation tree.
 */
@ApiModel(description = "The campaign position within the evaluation tree.")

public class CampaignEvaluationPosition {
  public static final String SERIALIZED_NAME_GROUP_ID = "groupId";
  @SerializedName(SERIALIZED_NAME_GROUP_ID)
  private Integer groupId;

  public static final String SERIALIZED_NAME_GROUP_NAME = "groupName";
  @SerializedName(SERIALIZED_NAME_GROUP_NAME)
  private String groupName;

  public static final String SERIALIZED_NAME_POSITION = "position";
  @SerializedName(SERIALIZED_NAME_POSITION)
  private Integer position;


  public CampaignEvaluationPosition groupId(Integer groupId) {
    
    this.groupId = groupId;
    return this;
  }

   /**
   * The ID of the campaign evaluation group the campaign belongs to.
   * @return groupId
  **/
  @ApiModelProperty(example = "2", required = true, value = "The ID of the campaign evaluation group the campaign belongs to.")

  public Integer getGroupId() {
    return groupId;
  }


  public void setGroupId(Integer groupId) {
    this.groupId = groupId;
  }


  public CampaignEvaluationPosition groupName(String groupName) {
    
    this.groupName = groupName;
    return this;
  }

   /**
   * The name of the campaign evaluation group the campaign belongs to.
   * @return groupName
  **/
  @ApiModelProperty(example = "Summer campaigns", required = true, value = "The name of the campaign evaluation group the campaign belongs to.")

  public String getGroupName() {
    return groupName;
  }


  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }


  public CampaignEvaluationPosition position(Integer position) {
    
    this.position = position;
    return this;
  }

   /**
   * The position of the campaign node in its parent group.
   * @return position
  **/
  @ApiModelProperty(example = "2", required = true, value = "The position of the campaign node in its parent group.")

  public Integer getPosition() {
    return position;
  }


  public void setPosition(Integer position) {
    this.position = position;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignEvaluationPosition campaignEvaluationPosition = (CampaignEvaluationPosition) o;
    return Objects.equals(this.groupId, campaignEvaluationPosition.groupId) &&
        Objects.equals(this.groupName, campaignEvaluationPosition.groupName) &&
        Objects.equals(this.position, campaignEvaluationPosition.position);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupId, groupName, position);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignEvaluationPosition {\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

