/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import one.talon.model.CouponDeletionFilters;
import org.threeten.bp.OffsetDateTime;

/**
 * CouponDeletionJob
 */

public class CouponDeletionJob {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_APPLICATION_ID = "applicationId";
  @SerializedName(SERIALIZED_NAME_APPLICATION_ID)
  private Integer applicationId;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "accountId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  private Integer accountId;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  private CouponDeletionFilters filters;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_DELETED_AMOUNT = "deletedAmount";
  @SerializedName(SERIALIZED_NAME_DELETED_AMOUNT)
  private Integer deletedAmount;

  public static final String SERIALIZED_NAME_FAIL_COUNT = "failCount";
  @SerializedName(SERIALIZED_NAME_FAIL_COUNT)
  private Integer failCount;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<String> errors = new ArrayList<String>();

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private Integer createdBy;

  public static final String SERIALIZED_NAME_COMMUNICATED = "communicated";
  @SerializedName(SERIALIZED_NAME_COMMUNICATED)
  private Boolean communicated;

  public static final String SERIALIZED_NAME_CAMPAIGN_I_DS = "campaignIDs";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_I_DS)
  private List<Integer> campaignIDs = null;


  public CouponDeletionJob id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Internal ID of this entity.
   * @return id
  **/
  @ApiModelProperty(example = "6", required = true, value = "Internal ID of this entity.")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public CouponDeletionJob created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * The time this entity was created.
   * @return created
  **/
  @ApiModelProperty(example = "2020-06-10T09:05:27.993483Z", required = true, value = "The time this entity was created.")

  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public CouponDeletionJob applicationId(Integer applicationId) {
    
    this.applicationId = applicationId;
    return this;
  }

   /**
   * The ID of the Application that owns this entity.
   * @return applicationId
  **/
  @ApiModelProperty(example = "322", required = true, value = "The ID of the Application that owns this entity.")

  public Integer getApplicationId() {
    return applicationId;
  }


  public void setApplicationId(Integer applicationId) {
    this.applicationId = applicationId;
  }


  public CouponDeletionJob accountId(Integer accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * The ID of the account that owns this entity.
   * @return accountId
  **/
  @ApiModelProperty(example = "3886", required = true, value = "The ID of the account that owns this entity.")

  public Integer getAccountId() {
    return accountId;
  }


  public void setAccountId(Integer accountId) {
    this.accountId = accountId;
  }


  public CouponDeletionJob filters(CouponDeletionFilters filters) {
    
    this.filters = filters;
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @ApiModelProperty(required = true, value = "")

  public CouponDeletionFilters getFilters() {
    return filters;
  }


  public void setFilters(CouponDeletionFilters filters) {
    this.filters = filters;
  }


  public CouponDeletionJob status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * The current status of this request. Possible values: - &#x60;not_ready&#x60; - &#x60;pending&#x60; - &#x60;completed&#x60; - &#x60;failed&#x60; 
   * @return status
  **/
  @ApiModelProperty(example = "pending", required = true, value = "The current status of this request. Possible values: - `not_ready` - `pending` - `completed` - `failed` ")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public CouponDeletionJob deletedAmount(Integer deletedAmount) {
    
    this.deletedAmount = deletedAmount;
    return this;
  }

   /**
   * The number of coupon codes that were already deleted for this request.
   * @return deletedAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1000000", value = "The number of coupon codes that were already deleted for this request.")

  public Integer getDeletedAmount() {
    return deletedAmount;
  }


  public void setDeletedAmount(Integer deletedAmount) {
    this.deletedAmount = deletedAmount;
  }


  public CouponDeletionJob failCount(Integer failCount) {
    
    this.failCount = failCount;
    return this;
  }

   /**
   * The number of times this job failed.
   * @return failCount
  **/
  @ApiModelProperty(example = "10", required = true, value = "The number of times this job failed.")

  public Integer getFailCount() {
    return failCount;
  }


  public void setFailCount(Integer failCount) {
    this.failCount = failCount;
  }


  public CouponDeletionJob errors(List<String> errors) {
    
    this.errors = errors;
    return this;
  }

  public CouponDeletionJob addErrorsItem(String errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * An array of individual problems encountered during the request.
   * @return errors
  **/
  @ApiModelProperty(example = "[Connection to database was reset, failed to delete codes]", required = true, value = "An array of individual problems encountered during the request.")

  public List<String> getErrors() {
    return errors;
  }


  public void setErrors(List<String> errors) {
    this.errors = errors;
  }


  public CouponDeletionJob createdBy(Integer createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * ID of the user who created this effect.
   * @return createdBy
  **/
  @ApiModelProperty(example = "1", required = true, value = "ID of the user who created this effect.")

  public Integer getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(Integer createdBy) {
    this.createdBy = createdBy;
  }


  public CouponDeletionJob communicated(Boolean communicated) {
    
    this.communicated = communicated;
    return this;
  }

   /**
   * Indicates whether the user that created this job was notified of its final state.
   * @return communicated
  **/
  @ApiModelProperty(example = "false", required = true, value = "Indicates whether the user that created this job was notified of its final state.")

  public Boolean getCommunicated() {
    return communicated;
  }


  public void setCommunicated(Boolean communicated) {
    this.communicated = communicated;
  }


  public CouponDeletionJob campaignIDs(List<Integer> campaignIDs) {
    
    this.campaignIDs = campaignIDs;
    return this;
  }

  public CouponDeletionJob addCampaignIDsItem(Integer campaignIDsItem) {
    if (this.campaignIDs == null) {
      this.campaignIDs = new ArrayList<Integer>();
    }
    this.campaignIDs.add(campaignIDsItem);
    return this;
  }

   /**
   * Get campaignIDs
   * @return campaignIDs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getCampaignIDs() {
    return campaignIDs;
  }


  public void setCampaignIDs(List<Integer> campaignIDs) {
    this.campaignIDs = campaignIDs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponDeletionJob couponDeletionJob = (CouponDeletionJob) o;
    return Objects.equals(this.id, couponDeletionJob.id) &&
        Objects.equals(this.created, couponDeletionJob.created) &&
        Objects.equals(this.applicationId, couponDeletionJob.applicationId) &&
        Objects.equals(this.accountId, couponDeletionJob.accountId) &&
        Objects.equals(this.filters, couponDeletionJob.filters) &&
        Objects.equals(this.status, couponDeletionJob.status) &&
        Objects.equals(this.deletedAmount, couponDeletionJob.deletedAmount) &&
        Objects.equals(this.failCount, couponDeletionJob.failCount) &&
        Objects.equals(this.errors, couponDeletionJob.errors) &&
        Objects.equals(this.createdBy, couponDeletionJob.createdBy) &&
        Objects.equals(this.communicated, couponDeletionJob.communicated) &&
        Objects.equals(this.campaignIDs, couponDeletionJob.campaignIDs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, created, applicationId, accountId, filters, status, deletedAmount, failCount, errors, createdBy, communicated, campaignIDs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponDeletionJob {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    deletedAmount: ").append(toIndentedString(deletedAmount)).append("\n");
    sb.append("    failCount: ").append(toIndentedString(failCount)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    communicated: ").append(toIndentedString(communicated)).append("\n");
    sb.append("    campaignIDs: ").append(toIndentedString(campaignIDs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

