/*
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import one.talon.model.AdditionalCost;
import one.talon.model.CartItem;
import org.threeten.bp.OffsetDateTime;

/**
 * 
 */
@ApiModel(description = "")

public class CustomerSessionV2 {
  public static final String SERIALIZED_NAME_INTEGRATION_ID = "integrationId";
  @SerializedName(SERIALIZED_NAME_INTEGRATION_ID)
  private String integrationId;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_APPLICATION_ID = "applicationId";
  @SerializedName(SERIALIZED_NAME_APPLICATION_ID)
  private Integer applicationId;

  public static final String SERIALIZED_NAME_PROFILE_ID = "profileId";
  @SerializedName(SERIALIZED_NAME_PROFILE_ID)
  private String profileId;

  public static final String SERIALIZED_NAME_COUPON_CODES = "couponCodes";
  @SerializedName(SERIALIZED_NAME_COUPON_CODES)
  private List<String> couponCodes = null;

  public static final String SERIALIZED_NAME_REFERRAL_CODE = "referralCode";
  @SerializedName(SERIALIZED_NAME_REFERRAL_CODE)
  private String referralCode;

  /**
   * Indicates the current state of the session. All sessions must start in the \&quot;open\&quot; state, after which valid transitions are...  1. open -&gt; closed 2. open -&gt; cancelled 3. closed -&gt; cancelled 
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    OPEN("open"),
    
    CLOSED("closed"),
    
    CANCELLED("cancelled");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StateEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private StateEnum state = StateEnum.OPEN;

  public static final String SERIALIZED_NAME_CART_ITEMS = "cartItems";
  @SerializedName(SERIALIZED_NAME_CART_ITEMS)
  private List<CartItem> cartItems = new ArrayList<CartItem>();

  public static final String SERIALIZED_NAME_ADDITIONAL_COSTS = "additionalCosts";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_COSTS)
  private Map<String, AdditionalCost> additionalCosts = null;

  public static final String SERIALIZED_NAME_IDENTIFIERS = "identifiers";
  @SerializedName(SERIALIZED_NAME_IDENTIFIERS)
  private List<String> identifiers = null;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private Object attributes;

  public static final String SERIALIZED_NAME_FIRST_SESSION = "firstSession";
  @SerializedName(SERIALIZED_NAME_FIRST_SESSION)
  private Boolean firstSession;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private BigDecimal total;

  public static final String SERIALIZED_NAME_CART_ITEM_TOTAL = "cartItemTotal";
  @SerializedName(SERIALIZED_NAME_CART_ITEM_TOTAL)
  private BigDecimal cartItemTotal;

  public static final String SERIALIZED_NAME_ADDITIONAL_COST_TOTAL = "additionalCostTotal";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_COST_TOTAL)
  private BigDecimal additionalCostTotal;


  public CustomerSessionV2 integrationId(String integrationId) {
    
    this.integrationId = integrationId;
    return this;
  }

   /**
   * The ID used for this entity in the application system.
   * @return integrationId
  **/
  @ApiModelProperty(required = true, value = "The ID used for this entity in the application system.")

  public String getIntegrationId() {
    return integrationId;
  }


  public void setIntegrationId(String integrationId) {
    this.integrationId = integrationId;
  }


  public CustomerSessionV2 created(OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * The exact moment this entity was created.
   * @return created
  **/
  @ApiModelProperty(required = true, value = "The exact moment this entity was created.")

  public OffsetDateTime getCreated() {
    return created;
  }


  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }


  public CustomerSessionV2 applicationId(Integer applicationId) {
    
    this.applicationId = applicationId;
    return this;
  }

   /**
   * The ID of the application that owns this entity.
   * @return applicationId
  **/
  @ApiModelProperty(required = true, value = "The ID of the application that owns this entity.")

  public Integer getApplicationId() {
    return applicationId;
  }


  public void setApplicationId(Integer applicationId) {
    this.applicationId = applicationId;
  }


  public CustomerSessionV2 profileId(String profileId) {
    
    this.profileId = profileId;
    return this;
  }

   /**
   * ID of the customers profile as used within this Talon.One account. May be omitted or set to the empty string if the customer does not yet have a known profile ID.
   * @return profileId
  **/
  @ApiModelProperty(required = true, value = "ID of the customers profile as used within this Talon.One account. May be omitted or set to the empty string if the customer does not yet have a known profile ID.")

  public String getProfileId() {
    return profileId;
  }


  public void setProfileId(String profileId) {
    this.profileId = profileId;
  }


  public CustomerSessionV2 couponCodes(List<String> couponCodes) {
    
    this.couponCodes = couponCodes;
    return this;
  }

  public CustomerSessionV2 addCouponCodesItem(String couponCodesItem) {
    if (this.couponCodes == null) {
      this.couponCodes = new ArrayList<String>();
    }
    this.couponCodes.add(couponCodesItem);
    return this;
  }

   /**
   * Any coupon codes entered.
   * @return couponCodes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Any coupon codes entered.")

  public List<String> getCouponCodes() {
    return couponCodes;
  }


  public void setCouponCodes(List<String> couponCodes) {
    this.couponCodes = couponCodes;
  }


  public CustomerSessionV2 referralCode(String referralCode) {
    
    this.referralCode = referralCode;
    return this;
  }

   /**
   * Any referral code entered.
   * @return referralCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Any referral code entered.")

  public String getReferralCode() {
    return referralCode;
  }


  public void setReferralCode(String referralCode) {
    this.referralCode = referralCode;
  }


  public CustomerSessionV2 state(StateEnum state) {
    
    this.state = state;
    return this;
  }

   /**
   * Indicates the current state of the session. All sessions must start in the \&quot;open\&quot; state, after which valid transitions are...  1. open -&gt; closed 2. open -&gt; cancelled 3. closed -&gt; cancelled 
   * @return state
  **/
  @ApiModelProperty(required = true, value = "Indicates the current state of the session. All sessions must start in the \"open\" state, after which valid transitions are...  1. open -> closed 2. open -> cancelled 3. closed -> cancelled ")

  public StateEnum getState() {
    return state;
  }


  public void setState(StateEnum state) {
    this.state = state;
  }


  public CustomerSessionV2 cartItems(List<CartItem> cartItems) {
    
    this.cartItems = cartItems;
    return this;
  }

  public CustomerSessionV2 addCartItemsItem(CartItem cartItemsItem) {
    this.cartItems.add(cartItemsItem);
    return this;
  }

   /**
   * All items the customer will be purchasing in this session
   * @return cartItems
  **/
  @ApiModelProperty(required = true, value = "All items the customer will be purchasing in this session")

  public List<CartItem> getCartItems() {
    return cartItems;
  }


  public void setCartItems(List<CartItem> cartItems) {
    this.cartItems = cartItems;
  }


  public CustomerSessionV2 additionalCosts(Map<String, AdditionalCost> additionalCosts) {
    
    this.additionalCosts = additionalCosts;
    return this;
  }

  public CustomerSessionV2 putAdditionalCostsItem(String key, AdditionalCost additionalCostsItem) {
    if (this.additionalCosts == null) {
      this.additionalCosts = new HashMap<String, AdditionalCost>();
    }
    this.additionalCosts.put(key, additionalCostsItem);
    return this;
  }

   /**
   * Any costs associated with the session that can not be explicitly attributed to cart items. Examples include shipping costs and service fees.
   * @return additionalCosts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Any costs associated with the session that can not be explicitly attributed to cart items. Examples include shipping costs and service fees.")

  public Map<String, AdditionalCost> getAdditionalCosts() {
    return additionalCosts;
  }


  public void setAdditionalCosts(Map<String, AdditionalCost> additionalCosts) {
    this.additionalCosts = additionalCosts;
  }


  public CustomerSessionV2 identifiers(List<String> identifiers) {
    
    this.identifiers = identifiers;
    return this;
  }

  public CustomerSessionV2 addIdentifiersItem(String identifiersItem) {
    if (this.identifiers == null) {
      this.identifiers = new ArrayList<String>();
    }
    this.identifiers.add(identifiersItem);
    return this;
  }

   /**
   * Identifiers for the customer, this can be used for limits on values such as device ID.
   * @return identifiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifiers for the customer, this can be used for limits on values such as device ID.")

  public List<String> getIdentifiers() {
    return identifiers;
  }


  public void setIdentifiers(List<String> identifiers) {
    this.identifiers = identifiers;
  }


  public CustomerSessionV2 attributes(Object attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * A key-value map of the sessions attributes. The potentially valid attributes are configured in your accounts developer settings. 
   * @return attributes
  **/
  @ApiModelProperty(required = true, value = "A key-value map of the sessions attributes. The potentially valid attributes are configured in your accounts developer settings. ")

  public Object getAttributes() {
    return attributes;
  }


  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }


  public CustomerSessionV2 firstSession(Boolean firstSession) {
    
    this.firstSession = firstSession;
    return this;
  }

   /**
   * Indicates whether this is the first session for the customer&#39;s profile. Will always be true for anonymous sessions.
   * @return firstSession
  **/
  @ApiModelProperty(required = true, value = "Indicates whether this is the first session for the customer's profile. Will always be true for anonymous sessions.")

  public Boolean getFirstSession() {
    return firstSession;
  }


  public void setFirstSession(Boolean firstSession) {
    this.firstSession = firstSession;
  }


  public CustomerSessionV2 total(BigDecimal total) {
    
    this.total = total;
    return this;
  }

   /**
   * The total sum of cart-items, as well as additional costs, before any discounts applied
   * @return total
  **/
  @ApiModelProperty(required = true, value = "The total sum of cart-items, as well as additional costs, before any discounts applied")

  public BigDecimal getTotal() {
    return total;
  }


  public void setTotal(BigDecimal total) {
    this.total = total;
  }


  public CustomerSessionV2 cartItemTotal(BigDecimal cartItemTotal) {
    
    this.cartItemTotal = cartItemTotal;
    return this;
  }

   /**
   * The total sum of cart-items before any discounts applied
   * @return cartItemTotal
  **/
  @ApiModelProperty(required = true, value = "The total sum of cart-items before any discounts applied")

  public BigDecimal getCartItemTotal() {
    return cartItemTotal;
  }


  public void setCartItemTotal(BigDecimal cartItemTotal) {
    this.cartItemTotal = cartItemTotal;
  }


  public CustomerSessionV2 additionalCostTotal(BigDecimal additionalCostTotal) {
    
    this.additionalCostTotal = additionalCostTotal;
    return this;
  }

   /**
   * The total sum of additional costs before any discounts applied
   * @return additionalCostTotal
  **/
  @ApiModelProperty(required = true, value = "The total sum of additional costs before any discounts applied")

  public BigDecimal getAdditionalCostTotal() {
    return additionalCostTotal;
  }


  public void setAdditionalCostTotal(BigDecimal additionalCostTotal) {
    this.additionalCostTotal = additionalCostTotal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerSessionV2 customerSessionV2 = (CustomerSessionV2) o;
    return Objects.equals(this.integrationId, customerSessionV2.integrationId) &&
        Objects.equals(this.created, customerSessionV2.created) &&
        Objects.equals(this.applicationId, customerSessionV2.applicationId) &&
        Objects.equals(this.profileId, customerSessionV2.profileId) &&
        Objects.equals(this.couponCodes, customerSessionV2.couponCodes) &&
        Objects.equals(this.referralCode, customerSessionV2.referralCode) &&
        Objects.equals(this.state, customerSessionV2.state) &&
        Objects.equals(this.cartItems, customerSessionV2.cartItems) &&
        Objects.equals(this.additionalCosts, customerSessionV2.additionalCosts) &&
        Objects.equals(this.identifiers, customerSessionV2.identifiers) &&
        Objects.equals(this.attributes, customerSessionV2.attributes) &&
        Objects.equals(this.firstSession, customerSessionV2.firstSession) &&
        Objects.equals(this.total, customerSessionV2.total) &&
        Objects.equals(this.cartItemTotal, customerSessionV2.cartItemTotal) &&
        Objects.equals(this.additionalCostTotal, customerSessionV2.additionalCostTotal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(integrationId, created, applicationId, profileId, couponCodes, referralCode, state, cartItems, additionalCosts, identifiers, attributes, firstSession, total, cartItemTotal, additionalCostTotal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerSessionV2 {\n");
    sb.append("    integrationId: ").append(toIndentedString(integrationId)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    couponCodes: ").append(toIndentedString(couponCodes)).append("\n");
    sb.append("    referralCode: ").append(toIndentedString(referralCode)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    cartItems: ").append(toIndentedString(cartItems)).append("\n");
    sb.append("    additionalCosts: ").append(toIndentedString(additionalCosts)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    firstSession: ").append(toIndentedString(firstSession)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    cartItemTotal: ").append(toIndentedString(cartItemTotal)).append("\n");
    sb.append("    additionalCostTotal: ").append(toIndentedString(additionalCostTotal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

