/*
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * The properties specific to the \&quot;deductLoyaltyPoints\&quot; effect. This gets triggered whenever a validated rule contained a condition to only trigger when the given number of loyalty points could be deduced. These points are automatically stored and managed inside Talon.One.
 */
@ApiModel(description = "The properties specific to the \"deductLoyaltyPoints\" effect. This gets triggered whenever a validated rule contained a condition to only trigger when the given number of loyalty points could be deduced. These points are automatically stored and managed inside Talon.One.")

public class DeductLoyaltyPointsEffectProps {
  public static final String SERIALIZED_NAME_RULE_TITLE = "ruleTitle";
  @SerializedName(SERIALIZED_NAME_RULE_TITLE)
  private String ruleTitle;

  public static final String SERIALIZED_NAME_PROGRAM_ID = "programId";
  @SerializedName(SERIALIZED_NAME_PROGRAM_ID)
  private Integer programId;

  public static final String SERIALIZED_NAME_SUB_LEDGER_ID = "subLedgerId";
  @SerializedName(SERIALIZED_NAME_SUB_LEDGER_ID)
  private String subLedgerId;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private BigDecimal value;


  public DeductLoyaltyPointsEffectProps ruleTitle(String ruleTitle) {
    
    this.ruleTitle = ruleTitle;
    return this;
  }

   /**
   * The title of the rule that contained triggered this points deduction
   * @return ruleTitle
  **/
  @ApiModelProperty(required = true, value = "The title of the rule that contained triggered this points deduction")

  public String getRuleTitle() {
    return ruleTitle;
  }


  public void setRuleTitle(String ruleTitle) {
    this.ruleTitle = ruleTitle;
  }


  public DeductLoyaltyPointsEffectProps programId(Integer programId) {
    
    this.programId = programId;
    return this;
  }

   /**
   * The ID of the loyalty program where these points were added
   * @return programId
  **/
  @ApiModelProperty(required = true, value = "The ID of the loyalty program where these points were added")

  public Integer getProgramId() {
    return programId;
  }


  public void setProgramId(Integer programId) {
    this.programId = programId;
  }


  public DeductLoyaltyPointsEffectProps subLedgerId(String subLedgerId) {
    
    this.subLedgerId = subLedgerId;
    return this;
  }

   /**
   * The ID of the subledger within the loyalty program where these points were added
   * @return subLedgerId
  **/
  @ApiModelProperty(required = true, value = "The ID of the subledger within the loyalty program where these points were added")

  public String getSubLedgerId() {
    return subLedgerId;
  }


  public void setSubLedgerId(String subLedgerId) {
    this.subLedgerId = subLedgerId;
  }


  public DeductLoyaltyPointsEffectProps value(BigDecimal value) {
    
    this.value = value;
    return this;
  }

   /**
   * The amount of points that were deducted
   * @return value
  **/
  @ApiModelProperty(required = true, value = "The amount of points that were deducted")

  public BigDecimal getValue() {
    return value;
  }


  public void setValue(BigDecimal value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeductLoyaltyPointsEffectProps deductLoyaltyPointsEffectProps = (DeductLoyaltyPointsEffectProps) o;
    return Objects.equals(this.ruleTitle, deductLoyaltyPointsEffectProps.ruleTitle) &&
        Objects.equals(this.programId, deductLoyaltyPointsEffectProps.programId) &&
        Objects.equals(this.subLedgerId, deductLoyaltyPointsEffectProps.subLedgerId) &&
        Objects.equals(this.value, deductLoyaltyPointsEffectProps.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ruleTitle, programId, subLedgerId, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeductLoyaltyPointsEffectProps {\n");
    sb.append("    ruleTitle: ").append(toIndentedString(ruleTitle)).append("\n");
    sb.append("    programId: ").append(toIndentedString(programId)).append("\n");
    sb.append("    subLedgerId: ").append(toIndentedString(subLedgerId)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

