/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://mycompany.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import one.talon.model.LoyaltyBalance;

/**
 * List of loyalty balances for a ledger and its subledgers.
 */
@ApiModel(description = "List of loyalty balances for a ledger and its subledgers.")

public class LoyaltyBalances {
  public static final String SERIALIZED_NAME_BALANCE = "balance";
  @SerializedName(SERIALIZED_NAME_BALANCE)
  private LoyaltyBalance balance;

  public static final String SERIALIZED_NAME_SUBLEDGER_BALANCES = "subledgerBalances";
  @SerializedName(SERIALIZED_NAME_SUBLEDGER_BALANCES)
  private Map<String, LoyaltyBalance> subledgerBalances = null;


  public LoyaltyBalances balance(LoyaltyBalance balance) {
    
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LoyaltyBalance getBalance() {
    return balance;
  }


  public void setBalance(LoyaltyBalance balance) {
    this.balance = balance;
  }


  public LoyaltyBalances subledgerBalances(Map<String, LoyaltyBalance> subledgerBalances) {
    
    this.subledgerBalances = subledgerBalances;
    return this;
  }

  public LoyaltyBalances putSubledgerBalancesItem(String key, LoyaltyBalance subledgerBalancesItem) {
    if (this.subledgerBalances == null) {
      this.subledgerBalances = new HashMap<String, LoyaltyBalance>();
    }
    this.subledgerBalances.put(key, subledgerBalancesItem);
    return this;
  }

   /**
   * Map of the loyalty balances of the subledgers of a ledger.
   * @return subledgerBalances
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"mysubledger\":{\"activePoints\":286,\"pendingPoints\":50,\"spentPoints\":150,\"expiredPoints\":25}}", value = "Map of the loyalty balances of the subledgers of a ledger.")

  public Map<String, LoyaltyBalance> getSubledgerBalances() {
    return subledgerBalances;
  }


  public void setSubledgerBalances(Map<String, LoyaltyBalance> subledgerBalances) {
    this.subledgerBalances = subledgerBalances;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoyaltyBalances loyaltyBalances = (LoyaltyBalances) o;
    return Objects.equals(this.balance, loyaltyBalances.balance) &&
        Objects.equals(this.subledgerBalances, loyaltyBalances.subledgerBalances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balance, subledgerBalances);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoyaltyBalances {\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    subledgerBalances: ").append(toIndentedString(subledgerBalances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

