/*
 * Talon.One API
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation--v1-customer_profiles--integrationId--put 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import one.talon.model.CouponRejectionReason;
import one.talon.model.ReferralRejectionReason;

/**
 * Meta
 */

public class Meta {
  public static final String SERIALIZED_NAME_CAMPAIGNS = "campaigns";
  @SerializedName(SERIALIZED_NAME_CAMPAIGNS)
  private Map<String, Object> campaigns = null;

  public static final String SERIALIZED_NAME_COUPONS = "coupons";
  @SerializedName(SERIALIZED_NAME_COUPONS)
  private Map<String, Object> coupons = null;

  public static final String SERIALIZED_NAME_COUPON_REJECTION_REASON = "couponRejectionReason";
  @SerializedName(SERIALIZED_NAME_COUPON_REJECTION_REASON)
  private CouponRejectionReason couponRejectionReason;

  public static final String SERIALIZED_NAME_REFERRAL_REJECTION_REASON = "referralRejectionReason";
  @SerializedName(SERIALIZED_NAME_REFERRAL_REJECTION_REASON)
  private ReferralRejectionReason referralRejectionReason;

  public static final String SERIALIZED_NAME_WARNINGS = "warnings";
  @SerializedName(SERIALIZED_NAME_WARNINGS)
  private Map<String, Object> warnings = null;


  public Meta campaigns(Map<String, Object> campaigns) {
    
    this.campaigns = campaigns;
    return this;
  }

  public Meta putCampaignsItem(String key, Object campaignsItem) {
    if (this.campaigns == null) {
      this.campaigns = new HashMap<String, Object>();
    }
    this.campaigns.put(key, campaignsItem);
    return this;
  }

   /**
   * Maps each evaluated campaign ID to a key-value list of that campaigns attributes. Campaigns without attributes will be omitted.
   * @return campaigns
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Maps each evaluated campaign ID to a key-value list of that campaigns attributes. Campaigns without attributes will be omitted.")

  public Map<String, Object> getCampaigns() {
    return campaigns;
  }


  public void setCampaigns(Map<String, Object> campaigns) {
    this.campaigns = campaigns;
  }


  public Meta coupons(Map<String, Object> coupons) {
    
    this.coupons = coupons;
    return this;
  }

  public Meta putCouponsItem(String key, Object couponsItem) {
    if (this.coupons == null) {
      this.coupons = new HashMap<String, Object>();
    }
    this.coupons.put(key, couponsItem);
    return this;
  }

   /**
   * Maps the coupon value to a key-value list of that coupons attributes.
   * @return coupons
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Maps the coupon value to a key-value list of that coupons attributes.")

  public Map<String, Object> getCoupons() {
    return coupons;
  }


  public void setCoupons(Map<String, Object> coupons) {
    this.coupons = coupons;
  }


  public Meta couponRejectionReason(CouponRejectionReason couponRejectionReason) {
    
    this.couponRejectionReason = couponRejectionReason;
    return this;
  }

   /**
   * Get couponRejectionReason
   * @return couponRejectionReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CouponRejectionReason getCouponRejectionReason() {
    return couponRejectionReason;
  }


  public void setCouponRejectionReason(CouponRejectionReason couponRejectionReason) {
    this.couponRejectionReason = couponRejectionReason;
  }


  public Meta referralRejectionReason(ReferralRejectionReason referralRejectionReason) {
    
    this.referralRejectionReason = referralRejectionReason;
    return this;
  }

   /**
   * Get referralRejectionReason
   * @return referralRejectionReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ReferralRejectionReason getReferralRejectionReason() {
    return referralRejectionReason;
  }


  public void setReferralRejectionReason(ReferralRejectionReason referralRejectionReason) {
    this.referralRejectionReason = referralRejectionReason;
  }


  public Meta warnings(Map<String, Object> warnings) {
    
    this.warnings = warnings;
    return this;
  }

  public Meta putWarningsItem(String key, Object warningsItem) {
    if (this.warnings == null) {
      this.warnings = new HashMap<String, Object>();
    }
    this.warnings.put(key, warningsItem);
    return this;
  }

   /**
   * Contains warnings about possible misuse.
   * @return warnings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Contains warnings about possible misuse.")

  public Map<String, Object> getWarnings() {
    return warnings;
  }


  public void setWarnings(Map<String, Object> warnings) {
    this.warnings = warnings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Meta meta = (Meta) o;
    return Objects.equals(this.campaigns, meta.campaigns) &&
        Objects.equals(this.coupons, meta.coupons) &&
        Objects.equals(this.couponRejectionReason, meta.couponRejectionReason) &&
        Objects.equals(this.referralRejectionReason, meta.referralRejectionReason) &&
        Objects.equals(this.warnings, meta.warnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaigns, coupons, couponRejectionReason, referralRejectionReason, warnings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Meta {\n");
    sb.append("    campaigns: ").append(toIndentedString(campaigns)).append("\n");
    sb.append("    coupons: ").append(toIndentedString(coupons)).append("\n");
    sb.append("    couponRejectionReason: ").append(toIndentedString(couponRejectionReason)).append("\n");
    sb.append("    referralRejectionReason: ").append(toIndentedString(referralRejectionReason)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

