/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import one.talon.model.AttributesSettings;
import one.talon.model.LimitConfig;

/**
 * NewApplication
 */

public class NewApplication {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  private String timezone;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  /**
   * The case sensitivity behavior to check coupon codes in the campaigns of this Application.
   */
  @JsonAdapter(CaseSensitivityEnum.Adapter.class)
  public enum CaseSensitivityEnum {
    SENSITIVE("sensitive"),
    
    INSENSITIVE_UPPERCASE("insensitive-uppercase"),
    
    INSENSITIVE_LOWERCASE("insensitive-lowercase");

    private String value;

    CaseSensitivityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CaseSensitivityEnum fromValue(String value) {
      for (CaseSensitivityEnum b : CaseSensitivityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CaseSensitivityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CaseSensitivityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CaseSensitivityEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CaseSensitivityEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CASE_SENSITIVITY = "caseSensitivity";
  @SerializedName(SERIALIZED_NAME_CASE_SENSITIVITY)
  private CaseSensitivityEnum caseSensitivity;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private Object attributes;

  public static final String SERIALIZED_NAME_LIMITS = "limits";
  @SerializedName(SERIALIZED_NAME_LIMITS)
  private List<LimitConfig> limits = null;

  /**
   * The default scope to apply &#x60;setDiscount&#x60; effects on if no scope was provided with the effect. 
   */
  @JsonAdapter(DefaultDiscountScopeEnum.Adapter.class)
  public enum DefaultDiscountScopeEnum {
    SESSIONTOTAL("sessionTotal"),
    
    CARTITEMS("cartItems"),
    
    ADDITIONALCOSTS("additionalCosts");

    private String value;

    DefaultDiscountScopeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DefaultDiscountScopeEnum fromValue(String value) {
      for (DefaultDiscountScopeEnum b : DefaultDiscountScopeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DefaultDiscountScopeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DefaultDiscountScopeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DefaultDiscountScopeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DefaultDiscountScopeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_DEFAULT_DISCOUNT_SCOPE = "defaultDiscountScope";
  @SerializedName(SERIALIZED_NAME_DEFAULT_DISCOUNT_SCOPE)
  private DefaultDiscountScopeEnum defaultDiscountScope;

  public static final String SERIALIZED_NAME_ENABLE_CASCADING_DISCOUNTS = "enableCascadingDiscounts";
  @SerializedName(SERIALIZED_NAME_ENABLE_CASCADING_DISCOUNTS)
  private Boolean enableCascadingDiscounts;

  public static final String SERIALIZED_NAME_ENABLE_FLATTENED_CART_ITEMS = "enableFlattenedCartItems";
  @SerializedName(SERIALIZED_NAME_ENABLE_FLATTENED_CART_ITEMS)
  private Boolean enableFlattenedCartItems;

  public static final String SERIALIZED_NAME_ATTRIBUTES_SETTINGS = "attributesSettings";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES_SETTINGS)
  private AttributesSettings attributesSettings;

  public static final String SERIALIZED_NAME_SANDBOX = "sandbox";
  @SerializedName(SERIALIZED_NAME_SANDBOX)
  private Boolean sandbox;

  public static final String SERIALIZED_NAME_ENABLE_PARTIAL_DISCOUNTS = "enablePartialDiscounts";
  @SerializedName(SERIALIZED_NAME_ENABLE_PARTIAL_DISCOUNTS)
  private Boolean enablePartialDiscounts;

  /**
   * The default scope to apply &#x60;setDiscountPerItem&#x60; effects on if no scope was provided with the effect. 
   */
  @JsonAdapter(DefaultDiscountAdditionalCostPerItemScopeEnum.Adapter.class)
  public enum DefaultDiscountAdditionalCostPerItemScopeEnum {
    PRICE("price"),
    
    ITEMTOTAL("itemTotal"),
    
    ADDITIONALCOSTS("additionalCosts");

    private String value;

    DefaultDiscountAdditionalCostPerItemScopeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DefaultDiscountAdditionalCostPerItemScopeEnum fromValue(String value) {
      for (DefaultDiscountAdditionalCostPerItemScopeEnum b : DefaultDiscountAdditionalCostPerItemScopeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DefaultDiscountAdditionalCostPerItemScopeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DefaultDiscountAdditionalCostPerItemScopeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DefaultDiscountAdditionalCostPerItemScopeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DefaultDiscountAdditionalCostPerItemScopeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_DEFAULT_DISCOUNT_ADDITIONAL_COST_PER_ITEM_SCOPE = "defaultDiscountAdditionalCostPerItemScope";
  @SerializedName(SERIALIZED_NAME_DEFAULT_DISCOUNT_ADDITIONAL_COST_PER_ITEM_SCOPE)
  private DefaultDiscountAdditionalCostPerItemScopeEnum defaultDiscountAdditionalCostPerItemScope;

  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_ENABLE_CAMPAIGN_STATE_MANAGEMENT = "enableCampaignStateManagement";
  @SerializedName(SERIALIZED_NAME_ENABLE_CAMPAIGN_STATE_MANAGEMENT)
  private Boolean enableCampaignStateManagement;


  public NewApplication name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of this application.
   * @return name
  **/
  @ApiModelProperty(example = "My Application", required = true, value = "The name of this application.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public NewApplication description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A longer description of the application.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "A test Application", value = "A longer description of the application.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public NewApplication timezone(String timezone) {
    
    this.timezone = timezone;
    return this;
  }

   /**
   * A string containing an IANA timezone descriptor.
   * @return timezone
  **/
  @ApiModelProperty(example = "Europe/Berlin", required = true, value = "A string containing an IANA timezone descriptor.")

  public String getTimezone() {
    return timezone;
  }


  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }


  public NewApplication currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * The default currency for new customer sessions.
   * @return currency
  **/
  @ApiModelProperty(example = "EUR", required = true, value = "The default currency for new customer sessions.")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public NewApplication caseSensitivity(CaseSensitivityEnum caseSensitivity) {
    
    this.caseSensitivity = caseSensitivity;
    return this;
  }

   /**
   * The case sensitivity behavior to check coupon codes in the campaigns of this Application.
   * @return caseSensitivity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "sensitive", value = "The case sensitivity behavior to check coupon codes in the campaigns of this Application.")

  public CaseSensitivityEnum getCaseSensitivity() {
    return caseSensitivity;
  }


  public void setCaseSensitivity(CaseSensitivityEnum caseSensitivity) {
    this.caseSensitivity = caseSensitivity;
  }


  public NewApplication attributes(Object attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * Arbitrary properties associated with this campaign.
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Arbitrary properties associated with this campaign.")

  public Object getAttributes() {
    return attributes;
  }


  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }


  public NewApplication limits(List<LimitConfig> limits) {
    
    this.limits = limits;
    return this;
  }

  public NewApplication addLimitsItem(LimitConfig limitsItem) {
    if (this.limits == null) {
      this.limits = new ArrayList<LimitConfig>();
    }
    this.limits.add(limitsItem);
    return this;
  }

   /**
   * Default limits for campaigns created in this application.
   * @return limits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Default limits for campaigns created in this application.")

  public List<LimitConfig> getLimits() {
    return limits;
  }


  public void setLimits(List<LimitConfig> limits) {
    this.limits = limits;
  }


  public NewApplication defaultDiscountScope(DefaultDiscountScopeEnum defaultDiscountScope) {
    
    this.defaultDiscountScope = defaultDiscountScope;
    return this;
  }

   /**
   * The default scope to apply &#x60;setDiscount&#x60; effects on if no scope was provided with the effect. 
   * @return defaultDiscountScope
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The default scope to apply `setDiscount` effects on if no scope was provided with the effect. ")

  public DefaultDiscountScopeEnum getDefaultDiscountScope() {
    return defaultDiscountScope;
  }


  public void setDefaultDiscountScope(DefaultDiscountScopeEnum defaultDiscountScope) {
    this.defaultDiscountScope = defaultDiscountScope;
  }


  public NewApplication enableCascadingDiscounts(Boolean enableCascadingDiscounts) {
    
    this.enableCascadingDiscounts = enableCascadingDiscounts;
    return this;
  }

   /**
   * Indicates if discounts should cascade for this Application.
   * @return enableCascadingDiscounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates if discounts should cascade for this Application.")

  public Boolean getEnableCascadingDiscounts() {
    return enableCascadingDiscounts;
  }


  public void setEnableCascadingDiscounts(Boolean enableCascadingDiscounts) {
    this.enableCascadingDiscounts = enableCascadingDiscounts;
  }


  public NewApplication enableFlattenedCartItems(Boolean enableFlattenedCartItems) {
    
    this.enableFlattenedCartItems = enableFlattenedCartItems;
    return this;
  }

   /**
   * Indicates if cart items of quantity larger than one should be separated into different items of quantity one. 
   * @return enableFlattenedCartItems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates if cart items of quantity larger than one should be separated into different items of quantity one. ")

  public Boolean getEnableFlattenedCartItems() {
    return enableFlattenedCartItems;
  }


  public void setEnableFlattenedCartItems(Boolean enableFlattenedCartItems) {
    this.enableFlattenedCartItems = enableFlattenedCartItems;
  }


  public NewApplication attributesSettings(AttributesSettings attributesSettings) {
    
    this.attributesSettings = attributesSettings;
    return this;
  }

   /**
   * Get attributesSettings
   * @return attributesSettings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AttributesSettings getAttributesSettings() {
    return attributesSettings;
  }


  public void setAttributesSettings(AttributesSettings attributesSettings) {
    this.attributesSettings = attributesSettings;
  }


  public NewApplication sandbox(Boolean sandbox) {
    
    this.sandbox = sandbox;
    return this;
  }

   /**
   * Indicates if this is a live or sandbox Application.
   * @return sandbox
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates if this is a live or sandbox Application.")

  public Boolean getSandbox() {
    return sandbox;
  }


  public void setSandbox(Boolean sandbox) {
    this.sandbox = sandbox;
  }


  public NewApplication enablePartialDiscounts(Boolean enablePartialDiscounts) {
    
    this.enablePartialDiscounts = enablePartialDiscounts;
    return this;
  }

   /**
   * Indicates if this Application supports partial discounts.
   * @return enablePartialDiscounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates if this Application supports partial discounts.")

  public Boolean getEnablePartialDiscounts() {
    return enablePartialDiscounts;
  }


  public void setEnablePartialDiscounts(Boolean enablePartialDiscounts) {
    this.enablePartialDiscounts = enablePartialDiscounts;
  }


  public NewApplication defaultDiscountAdditionalCostPerItemScope(DefaultDiscountAdditionalCostPerItemScopeEnum defaultDiscountAdditionalCostPerItemScope) {
    
    this.defaultDiscountAdditionalCostPerItemScope = defaultDiscountAdditionalCostPerItemScope;
    return this;
  }

   /**
   * The default scope to apply &#x60;setDiscountPerItem&#x60; effects on if no scope was provided with the effect. 
   * @return defaultDiscountAdditionalCostPerItemScope
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The default scope to apply `setDiscountPerItem` effects on if no scope was provided with the effect. ")

  public DefaultDiscountAdditionalCostPerItemScopeEnum getDefaultDiscountAdditionalCostPerItemScope() {
    return defaultDiscountAdditionalCostPerItemScope;
  }


  public void setDefaultDiscountAdditionalCostPerItemScope(DefaultDiscountAdditionalCostPerItemScopeEnum defaultDiscountAdditionalCostPerItemScope) {
    this.defaultDiscountAdditionalCostPerItemScope = defaultDiscountAdditionalCostPerItemScope;
  }


  public NewApplication key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Hex key for HMAC-signing API calls as coming from this application (16 hex digits).
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Hex key for HMAC-signing API calls as coming from this application (16 hex digits).")

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public NewApplication enableCampaignStateManagement(Boolean enableCampaignStateManagement) {
    
    this.enableCampaignStateManagement = enableCampaignStateManagement;
    return this;
  }

   /**
   * Indicates whether the campaign staging and revisions feature is enabled for the Application.  **Important:** After this feature is enabled, it cannot be disabled. 
   * @return enableCampaignStateManagement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates whether the campaign staging and revisions feature is enabled for the Application.  **Important:** After this feature is enabled, it cannot be disabled. ")

  public Boolean getEnableCampaignStateManagement() {
    return enableCampaignStateManagement;
  }


  public void setEnableCampaignStateManagement(Boolean enableCampaignStateManagement) {
    this.enableCampaignStateManagement = enableCampaignStateManagement;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewApplication newApplication = (NewApplication) o;
    return Objects.equals(this.name, newApplication.name) &&
        Objects.equals(this.description, newApplication.description) &&
        Objects.equals(this.timezone, newApplication.timezone) &&
        Objects.equals(this.currency, newApplication.currency) &&
        Objects.equals(this.caseSensitivity, newApplication.caseSensitivity) &&
        Objects.equals(this.attributes, newApplication.attributes) &&
        Objects.equals(this.limits, newApplication.limits) &&
        Objects.equals(this.defaultDiscountScope, newApplication.defaultDiscountScope) &&
        Objects.equals(this.enableCascadingDiscounts, newApplication.enableCascadingDiscounts) &&
        Objects.equals(this.enableFlattenedCartItems, newApplication.enableFlattenedCartItems) &&
        Objects.equals(this.attributesSettings, newApplication.attributesSettings) &&
        Objects.equals(this.sandbox, newApplication.sandbox) &&
        Objects.equals(this.enablePartialDiscounts, newApplication.enablePartialDiscounts) &&
        Objects.equals(this.defaultDiscountAdditionalCostPerItemScope, newApplication.defaultDiscountAdditionalCostPerItemScope) &&
        Objects.equals(this.key, newApplication.key) &&
        Objects.equals(this.enableCampaignStateManagement, newApplication.enableCampaignStateManagement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, timezone, currency, caseSensitivity, attributes, limits, defaultDiscountScope, enableCascadingDiscounts, enableFlattenedCartItems, attributesSettings, sandbox, enablePartialDiscounts, defaultDiscountAdditionalCostPerItemScope, key, enableCampaignStateManagement);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewApplication {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    caseSensitivity: ").append(toIndentedString(caseSensitivity)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("    defaultDiscountScope: ").append(toIndentedString(defaultDiscountScope)).append("\n");
    sb.append("    enableCascadingDiscounts: ").append(toIndentedString(enableCascadingDiscounts)).append("\n");
    sb.append("    enableFlattenedCartItems: ").append(toIndentedString(enableFlattenedCartItems)).append("\n");
    sb.append("    attributesSettings: ").append(toIndentedString(attributesSettings)).append("\n");
    sb.append("    sandbox: ").append(toIndentedString(sandbox)).append("\n");
    sb.append("    enablePartialDiscounts: ").append(toIndentedString(enablePartialDiscounts)).append("\n");
    sb.append("    defaultDiscountAdditionalCostPerItemScope: ").append(toIndentedString(defaultDiscountAdditionalCostPerItemScope)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    enableCampaignStateManagement: ").append(toIndentedString(enableCampaignStateManagement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

