/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import one.talon.custom.JsonNullable;
import one.talon.custom.NullableAdapterFactory;

/**
 * The specific properties of the \&quot;PATCH\&quot; catalog sync action.
 */
@ApiModel(description = "The specific properties of the \"PATCH\" catalog sync action.")
@JsonAdapter(NullableAdapterFactory.class)

public class PatchItemCatalogAction {
  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  private String sku;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private BigDecimal price;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
    /*allow Serializing null for this field */
      @JsonNullable
  private Object attributes;

  public static final String SERIALIZED_NAME_CREATE_IF_NOT_EXISTS = "createIfNotExists";
  @SerializedName(SERIALIZED_NAME_CREATE_IF_NOT_EXISTS)
  private Boolean createIfNotExists = false;


  public PatchItemCatalogAction sku(String sku) {
    
    this.sku = sku;
    return this;
  }

   /**
   * The unique SKU of the item to patch.
   * @return sku
  **/
  @ApiModelProperty(required = true, value = "The unique SKU of the item to patch.")

  public String getSku() {
    return sku;
  }


  public void setSku(String sku) {
    this.sku = sku;
  }


  public PatchItemCatalogAction price(BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * Price of the item.
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "99.99", value = "Price of the item.")

  public BigDecimal getPrice() {
    return price;
  }


  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  public PatchItemCatalogAction attributes(Object attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * The attributes of the item to patch.
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The attributes of the item to patch.")

  public Object getAttributes() {
    return attributes;
  }


  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }


  public PatchItemCatalogAction createIfNotExists(Boolean createIfNotExists) {
    
    this.createIfNotExists = createIfNotExists;
    return this;
  }

   /**
   * Indicates whether to create an item if the SKU does not exist.
   * @return createIfNotExists
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether to create an item if the SKU does not exist.")

  public Boolean getCreateIfNotExists() {
    return createIfNotExists;
  }


  public void setCreateIfNotExists(Boolean createIfNotExists) {
    this.createIfNotExists = createIfNotExists;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchItemCatalogAction patchItemCatalogAction = (PatchItemCatalogAction) o;
    return Objects.equals(this.sku, patchItemCatalogAction.sku) &&
        Objects.equals(this.price, patchItemCatalogAction.price) &&
        Objects.equals(this.attributes, patchItemCatalogAction.attributes) &&
        Objects.equals(this.createIfNotExists, patchItemCatalogAction.createIfNotExists);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sku, price, attributes, createIfNotExists);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchItemCatalogAction {\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    createIfNotExists: ").append(toIndentedString(createIfNotExists)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

