/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PlaceholderDetails
 */

public class PlaceholderDetails {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private List<Object> value = new ArrayList<Object>();


  public PlaceholderDetails name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the placeholder.
   * @return name
  **/
  @ApiModelProperty(example = "my property", required = true, value = "The name of the placeholder.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public PlaceholderDetails type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of the value assigned to the placeholder.
   * @return type
  **/
  @ApiModelProperty(example = "list string", required = true, value = "The type of the value assigned to the placeholder.")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public PlaceholderDetails value(List<Object> value) {
    
    this.value = value;
    return this;
  }

  public PlaceholderDetails addValueItem(Object valueItem) {
    this.value.add(valueItem);
    return this;
  }

   /**
   * The current value of the placeholder.
   * @return value
  **/
  @ApiModelProperty(example = "[1, sku_value]", required = true, value = "The current value of the placeholder.")

  public List<Object> getValue() {
    return value;
  }


  public void setValue(List<Object> value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlaceholderDetails placeholderDetails = (PlaceholderDetails) o;
    return Objects.equals(this.name, placeholderDetails.name) &&
        Objects.equals(this.type, placeholderDetails.type) &&
        Objects.equals(this.value, placeholderDetails.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlaceholderDetails {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

