/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ResponseContentObject
 */

public class ResponseContentObject {
  /**
   * Gets or Sets responseContent
   */
  @JsonAdapter(ResponseContentEnum.Adapter.class)
  public enum ResponseContentEnum {
    CUSTOMERPROFILE("customerProfile"),
    
    TRIGGEREDCAMPAIGNS("triggeredCampaigns"),
    
    LOYALTY("loyalty"),
    
    EVENT("event"),
    
    AWARDEDGIVEAWAYS("awardedGiveaways"),
    
    RULEFAILUREREASONS("ruleFailureReasons");

    private String value;

    ResponseContentEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ResponseContentEnum fromValue(String value) {
      for (ResponseContentEnum b : ResponseContentEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ResponseContentEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ResponseContentEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ResponseContentEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ResponseContentEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_RESPONSE_CONTENT = "responseContent";
  @SerializedName(SERIALIZED_NAME_RESPONSE_CONTENT)
  private List<ResponseContentEnum> responseContent = null;


  public ResponseContentObject responseContent(List<ResponseContentEnum> responseContent) {
    
    this.responseContent = responseContent;
    return this;
  }

  public ResponseContentObject addResponseContentItem(ResponseContentEnum responseContentItem) {
    if (this.responseContent == null) {
      this.responseContent = new ArrayList<ResponseContentEnum>();
    }
    this.responseContent.add(responseContentItem);
    return this;
  }

   /**
   * Extends the response with the chosen data entities. Use this property to get as much data back as needed from one request instead of sending extra requests to other endpoints. 
   * @return responseContent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[triggeredCampaigns, customerProfile]", value = "Extends the response with the chosen data entities. Use this property to get as much data back as needed from one request instead of sending extra requests to other endpoints. ")

  public List<ResponseContentEnum> getResponseContent() {
    return responseContent;
  }


  public void setResponseContent(List<ResponseContentEnum> responseContent) {
    this.responseContent = responseContent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseContentObject responseContentObject = (ResponseContentObject) o;
    return Objects.equals(this.responseContent, responseContentObject.responseContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseContent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseContentObject {\n");
    sb.append("    responseContent: ").append(toIndentedString(responseContent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

