/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RuleMetadata
 */

public class RuleMetadata {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_DISPLAY_DESCRIPTION = "displayDescription";
  @SerializedName(SERIALIZED_NAME_DISPLAY_DESCRIPTION)
  private String displayDescription;

  public static final String SERIALIZED_NAME_RELATED_DATA = "relatedData";
  @SerializedName(SERIALIZED_NAME_RELATED_DATA)
  private String relatedData;


  public RuleMetadata title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * A short description of the rule.
   * @return title
  **/
  @ApiModelProperty(example = "Give discount via coupon", required = true, value = "A short description of the rule.")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public RuleMetadata displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * A customer-facing name for the rule.
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "20% off all shoes!", value = "A customer-facing name for the rule.")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public RuleMetadata displayDescription(String displayDescription) {
    
    this.displayDescription = displayDescription;
    return this;
  }

   /**
   * A customer-facing description that explains the details of the rule.   For example, this property can contain details about eligibility requirements, reward timelines, or terms and conditions. 
   * @return displayDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Get a 20% discount on all shoes during Thanksgiving! Offer valid till Dec 5 only.", value = "A customer-facing description that explains the details of the rule.   For example, this property can contain details about eligibility requirements, reward timelines, or terms and conditions. ")

  public String getDisplayDescription() {
    return displayDescription;
  }


  public void setDisplayDescription(String displayDescription) {
    this.displayDescription = displayDescription;
  }


  public RuleMetadata relatedData(String relatedData) {
    
    this.relatedData = relatedData;
    return this;
  }

   /**
   * Any additional data associated with the rule, such as an image URL, vendor name, or a content management system (CMS) ID. 
   * @return relatedData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://example.com/discounts/20-off-shoes.png", value = "Any additional data associated with the rule, such as an image URL, vendor name, or a content management system (CMS) ID. ")

  public String getRelatedData() {
    return relatedData;
  }


  public void setRelatedData(String relatedData) {
    this.relatedData = relatedData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleMetadata ruleMetadata = (RuleMetadata) o;
    return Objects.equals(this.title, ruleMetadata.title) &&
        Objects.equals(this.displayName, ruleMetadata.displayName) &&
        Objects.equals(this.displayDescription, ruleMetadata.displayDescription) &&
        Objects.equals(this.relatedData, ruleMetadata.relatedData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, displayName, displayDescription, relatedData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleMetadata {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    displayDescription: ").append(toIndentedString(displayDescription)).append("\n");
    sb.append("    relatedData: ").append(toIndentedString(relatedData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

