/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Configuration related to bulk operations, which allow multiple SCIM requests to be processed in a single HTTP request.
 */
@ApiModel(description = "Configuration related to bulk operations, which allow multiple SCIM requests to be processed in a single HTTP request.")

public class ScimServiceProviderConfigResponseBulk {
  public static final String SERIALIZED_NAME_MAX_OPERATIONS = "maxOperations";
  @SerializedName(SERIALIZED_NAME_MAX_OPERATIONS)
  private Integer maxOperations;

  public static final String SERIALIZED_NAME_MAX_PAYLOAD_SIZE = "maxPayloadSize";
  @SerializedName(SERIALIZED_NAME_MAX_PAYLOAD_SIZE)
  private Integer maxPayloadSize;

  public static final String SERIALIZED_NAME_SUPPORTED = "supported";
  @SerializedName(SERIALIZED_NAME_SUPPORTED)
  private Boolean supported;


  public ScimServiceProviderConfigResponseBulk maxOperations(Integer maxOperations) {
    
    this.maxOperations = maxOperations;
    return this;
  }

   /**
   * The maximum number of individual operations that can be included in a single bulk request.
   * @return maxOperations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The maximum number of individual operations that can be included in a single bulk request.")

  public Integer getMaxOperations() {
    return maxOperations;
  }


  public void setMaxOperations(Integer maxOperations) {
    this.maxOperations = maxOperations;
  }


  public ScimServiceProviderConfigResponseBulk maxPayloadSize(Integer maxPayloadSize) {
    
    this.maxPayloadSize = maxPayloadSize;
    return this;
  }

   /**
   * The maximum size, in bytes, of the entire payload for a bulk operation request.
   * @return maxPayloadSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The maximum size, in bytes, of the entire payload for a bulk operation request.")

  public Integer getMaxPayloadSize() {
    return maxPayloadSize;
  }


  public void setMaxPayloadSize(Integer maxPayloadSize) {
    this.maxPayloadSize = maxPayloadSize;
  }


  public ScimServiceProviderConfigResponseBulk supported(Boolean supported) {
    
    this.supported = supported;
    return this;
  }

   /**
   * Indicates whether the SCIM service provider supports bulk operations.
   * @return supported
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether the SCIM service provider supports bulk operations.")

  public Boolean getSupported() {
    return supported;
  }


  public void setSupported(Boolean supported) {
    this.supported = supported;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScimServiceProviderConfigResponseBulk scimServiceProviderConfigResponseBulk = (ScimServiceProviderConfigResponseBulk) o;
    return Objects.equals(this.maxOperations, scimServiceProviderConfigResponseBulk.maxOperations) &&
        Objects.equals(this.maxPayloadSize, scimServiceProviderConfigResponseBulk.maxPayloadSize) &&
        Objects.equals(this.supported, scimServiceProviderConfigResponseBulk.supported);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxOperations, maxPayloadSize, supported);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScimServiceProviderConfigResponseBulk {\n");
    sb.append("    maxOperations: ").append(toIndentedString(maxOperations)).append("\n");
    sb.append("    maxPayloadSize: ").append(toIndentedString(maxPayloadSize)).append("\n");
    sb.append("    supported: ").append(toIndentedString(supported)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

